name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create buildozer.spec
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Autotyper' >> buildozer.spec
        echo 'package.name = autotyper' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo 'requirements = python3,kivy,requests' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[android]' >> buildozer.spec
        echo 'api = 33' >> buildozer.spec
        echo 'minapi = 21' >> buildozer.spec
        echo 'sdk_dir = %(home)s/.buildozer/android/platform/android-sdk' >> buildozer.spec

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-dev \
          python3-venv \
          zip \
          openjdk-11-jdk \
          git \
          wget \
          unzip

    - name: Install Python packages
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Setup Android SDK licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Создаем папку для лицензий
        mkdir -p ~/.android/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
        echo "d975f751698a77b662f1254ddbeed3901e976f5a" > ~/.android/licenses/intel-android-extra-license

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: autotyper-apk
        path: bin/*.apk
