name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create buildozer.spec
      run: |
        echo '[app]' > buildozer.spec
        echo 'title = Autotyper' >> buildozer.spec
        echo 'package.name = autotyper' >> buildozer.spec
        echo 'package.domain = org.example' >> buildozer.spec
        echo 'source.dir = .' >> buildozer.spec
        echo 'version = 0.1' >> buildozer.spec
        echo 'requirements = python3,kivy,requests' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[buildozer]' >> buildozer.spec
        echo 'log_level = 2' >> buildozer.spec
        echo '' >> buildozer.spec
        echo '[android]' >> buildozer.spec
        echo 'api = 33' >> buildozer.spec
        echo 'minapi = 21' >> buildozer.spec

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          zip \
          openjdk-11-jdk \
          wget \
          unzip

    - name: Install Buildozer
      run: |
        pip3 install buildozer

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Скачиваем и распаковываем Android SDK
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk
        unzip -q commandlinetools-linux-9477386_latest.zip -d android-sdk/cmdline-tools
        
        # Переименовываем папку правильно
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # Принимаем лицензии
        yes | sdkmanager --licenses
        
        # Устанавливаем необходимые пакеты
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: autotyper-apk
        path: bin/*.apk
