name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip openjdk-11-jdk git
          pip3 install buildozer cython
      - name: Create spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = Autotyper" >> buildozer.spec
          echo "package.name = autotyper" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "version = 0.1" >> buildozer.spec
          echo "requirements = python3,kivy" >> buildozer.spec
          echo "[android]" >> buildozer.spec
          echo "api = 30" >> buildozer.spec
          echo "minapi = 21" >> buildozer.spec
      - name: Build
        run: buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
