name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev python3-venv git
          pip3 install buildozer cython

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << 'EOF'
[app]
title = Autotyper
package.name = autotyper
package.domain = org.example
source.dir = .
version = 0.1
requirements = python3,kivy,requests

[android]
api = 33
minapi = 21
android.sdk_path = $ANDROID_SDK_ROOT
EOF

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: autotyper-apk
          path: bin/*.apk
