name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies for Ubuntu 24.04
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          python3-venv \
          swig \
          curl

    - name: Install Buildozer and dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython virtualenv

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: autotyper-apk
        path: bin/*.apk
        retention-days: 30
