name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix buildozer.spec
      run: |
        cat > buildozer.spec << EOF
[app]
title = Autotyper
package.name = autotyper
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf,json
version = 0.1
requirements = python3,kivy,requests

[buildozer]
log_level = 2

[android]
api = 33
minapi = 21
ndk = 25b

[android:meta-data]
android.app.uses_cleartext_traffic = true
EOF

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          zip \
          openjdk-11-jdk \
          wget \
          unzip

    - name: Install Buildozer
      run: |
        pip3 install buildozer

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | buildozer android licenses

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: autotyper-apk
        path: bin/*.apk
