name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-dev \
          python3-venv \
          zip \
          openjdk-11-jdk \
          git \
          wget \
          unzip

    - name: Install Python packages
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Setup Android SDK manually
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Скачиваем Android Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk
        unzip -q commandlinetools-linux-9477386_latest.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # Принимаем все лицензии автоматически
        yes | sdkmanager --licenses
        
        # Устанавливаем конкретные версии
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"
        
        # Копируем SDK в папку Buildozer
        mkdir -p ~/.buildozer/android/platform
        cp -r android-sdk ~/.buildozer/android/platform/android-sdk

    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
[app]
title = Autotyper
package.name = autotyper
package.domain = org.example
source.dir = .
version = 0.1
requirements = python3,kivy,requests

[buildozer]
log_level = 2

[android]
api = 33
minapi = 21
android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk
EOF

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: autotyper-apk
        path: bin/*.apk
